### ISSUE TITLE
How To Install This Repo

### ISSUE THREAD

**Issue by JnyJny** [Beau28713/Calculator_beau28713#2]
So normally, people aren't going to clone your repo, build a virtual environment, install the repo and dependencies just to run your shiny new tool.  All the cool kids package the repos so they can be distributed via PyPI. Speaking as a geek, there are few greater days than the first time you publish something to PyPI and then pip install it on you own machine. 

To get there from where you are now ( a bare `main.py` file ), you need to do a couple of things:
- [ ] Transform your main.py into a Python package.
- [ ] Create a pyproject.toml to describe your file.
- [ ] Create a driver script that calls your package.

The first one is pretty easy:

```console
$ mkdir calculator
$ mv main.py calculator/__main__.py
$ touch calculator/__init__.py
```

Next step is even easier (provided you have the tool `poetry` installed)
```console
$ py -m pip install poetry
$ cd repo_directory
$ poetry init
```
Answer the questions and then it writes the `pyproject.toml` for your repo. If you goof up, remove the pyproject.toml and re-create it. No harm no foul. And if you don't know exactly what your dependencies are, you can add them later. 

Finally, `poetry` will take care of creating and managing the driver script for you if you add the following to your pyproject.toml file:

```toml
[tool.poetry.scripts]
calculator = "calculator.__main__:main"
```
There are a couple of assumptions made here; first the package is called `calculator` and the `__main__.py` file has a function in it named `main`.

Once you have those things squared away, you can use poetry to manage the virtual environment while you are developing:
```console
$ cd repo
$  poetry shell
<penv> $ poetry install
```

This will create a virtual environment and then install your project and all it's dependencies into the new venv.

If you need to add dependencies, `poetry add <name>`. 

If you need to remove dependencies `poetry remove <name>`.

Publishing your package is pypi is pretty easy but requires some one-time setup; mainly you need to create an account pypi.org and update [poetry with your pypi credentials](https://python-poetry.org/docs/repositories/)

I know that's a lot all at once, but it makes your project more polished and enhances the installation experience for the people who use your tools.

**Comment by Beau28713** [comment]
Well that was a pain in the but, I learned some things I was doing wrong. But i got it done.
