### ISSUE TITLE
Cannot Install via PyPI

### ISSUE THREAD

**Issue by JnyJny** [Beau28713/Calculator_beau28713#4]
Good job getting your package published, unfortunately here's a bug report :)

```console
$ pip install calculator-beau28713
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.11,<4.0
ERROR: Could not find a version that satisfies the requirement calculator-beau28713 (from versions: none)
ERROR: No matching distribution found for calculator-beau28713
$ python3 --version
Python 3.10.7
```

Your project's  Python requirement (which are not part of the repo as far as I can tell) is so narrow that it precludes it from running on versions of Python less than 3.11 (3.10 in my case). Packages should try to specify the absolute minimum in terms of requirements to make it more convenient to use our code. If a package has dependencies, I tend to survey those dependencies and choose the minimum python version they require rather than pick whatever I have installed. 

Curious if you used a `pyproject.toml` to describe your package or `setup.py` (which is an older style)?

**Comment by Beau28713** [comment]
I used .toml, i ran into the same issue when installing it into my venv, I removed my python 3.10 version and installed 3.11. It worked then, im working on learning how to fix this issue s it will run on early version of python

**Comment by JnyJny** [comment]
Great! the pyproject.toml and poetry.lock files (assuming poetry) ought to be committed to the repo in addition to the code.

**Comment by Beau28713** [comment]
Okay so i have updated it to run on 3.9 up to 3.10.
